[package]
name = "omnichain-sdk"
version = "0.1.0"
authors = ["KOSASIH"]
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-std = "1.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
base64 = "0.13"
elliptic-curve = "0.10"
sha3 = "0.9"
hmac = "0.10"
aes-gcm = "0.9"
rand = "0.8"
log = "0.4"
tracing = "0.1"
tracing-futures = "0.2"

[features]
default = ["wallet", "api", "sdk"]
wallet = []
api = []
sdk = []

[lib]
name = "omnichain_sdk"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "omnichain-cli"
path = "src/main.rs"

[dev-dependencies]
mockito = "0.24"
tokio-mock = "0.1"
